[build]
  publish = "exampleSite/public"
  command = "npm install @splidejs/splide && cd exampleSite && hugo --gc --themesDir ../.. --config config.toml"

[build.environment]
  HUGO_VERSION = "0.78.2"
  HUGO_THEME = "repo"
